# Copy this file to `config.toml` and edit to match your local configuration.
root_dir = "E:/us-data-anon" # Root directory to the stored data.
output_dir = "E:/us-data-processed/"  # Where to save the processed data.

[pickle]
likely_us_images = "likely_us_images.pkl"
segmented_data = "segmented_data.pkl"
patient_paths = "patient_paths.pkl"
